### ISSUE TITLE
support for ODM v2.0?

### ISSUE THREAD

**Issue by DiTo97** [swhume/odmlib#15]
Hi. Thanks for the great work!

I was just wondering if the repository was still active and if support for [CIDSC ODM v2.0](https://www.cdisc.org/standards/data-exchange/odm-xml/odm-v2-0) specification is in the books or not.

**Comment by DiTo97** [comment]
@swhume, the [dedicated submodule](https://github.com/swhume/odmlib/tree/master/odmlib/odm_2_0) seems to be it, but is it mature and feature-rich?

**Comment by swhume** [comment]
Yes, I do plan to develop an ODM v2.0 model. We're in the process of finalizing the ODM v2.0 JSON specification, so that's been the delay. The ODM v2.0 team decided that they preferred to have a JSON model that's optimized for JSON and de-emphasized the ability to do round-tripping (easily convert back and forth between XML and JSON). That decision could complicate things a bit, but either way there will be an ODM v2.0 implementation that I'll start as soon as the JSON schemas are done.

**Comment by DiTo97** [comment]
Thanks for the response, @swhume.

On my side, it was more on how mature the current state of the library for v2.0. Personally, I don't mind either the XML or JSON structure as a tree structure is likely not suitable for our use case, which requires fast querying and comparison of clinical data, so we will likely have to perform an unnesting step to some suitable relational form, unless you know of something to that effect.

Therefore, my concern was more whether, given a generic record in ODM v2.0 reporting one or more studies, we would be able to parse its tree structure and access all the information it contains with the library in its current state.

**Comment by swhume** [comment]
I stopped working on it when ODM v2.0 changed direction for JSON and decided to create a different schema from the XML. I can revisit it and review it against the final ODM v2.0 spec and make the necessary updates. I believe I can get the XML version working quickly, then once the JSON schema is finalized we can figure out the best way to support it. You will still be able to generate JSON from the XML-focused model, but it won't match the new ODM v2.0 JSON schema.

**Comment by DiTo97** [comment]
@swhume, is there a way to extract the JSON schema associated to any study (one or more) defined inside the ODM file?

As we are looking for ways to integrate a FHIR datalake into an ODM extraction, it would be very helpful if there was a built-in way to extract the JSON schemas associated to all the studies defined inside the trial ODM file.

**Comment by DiTo97** [comment]
Any pointers on that, @swhume?

**Comment by swhume** [comment]
a few more details on what you're trying to do would be helpful. You can always email me at swhume at gmail dot com or post you can share those details here. Are you asking if you can generate a JSON schema for ODM (for the standard) that could be populated with FHIR? Or to extract ODM content (metadata and data) to transform into FHIR, or a way to transform ODM content into FHIR resources?
